### ISSUE TITLE
Reset other background color when replacing text with SVG

### ISSUE THREAD

**Issue by DivineDominion** [rougier/svg-lib#10]
I'm using modus-themes and recognized the colors that were showing through when I ran the demo .org file: that's the regular background colors of the org TODO keywords:

![Screen Shot 2021-10-02 at 07 47 50](https://user-images.githubusercontent.com/59080/135705402-49df9669-eff3-4b52-a8fd-810a03379416.png)
![Screen Shot 2021-10-02 at 07 47 55](https://user-images.githubusercontent.com/59080/135705403-3f026971-7438-42a1-b75c-e0eee2f2be48.png)

I increased `(setq line-spacing 10)` to make it more visible:

![Screen Shot 2021-10-02 at 07 49 12](https://user-images.githubusercontent.com/59080/135705404-3023aa26-4faf-496e-94bd-269fba7f1e85.png)

Without SVG but increased line spacing:

![Screen Shot 2021-10-02 at 07 58 10](https://user-images.githubusercontent.com/59080/135705426-62555e17-217d-48fc-be87-b7d27051322c.png)
![Screen Shot 2021-10-02 at 07 58 15](https://user-images.githubusercontent.com/59080/135705427-bb492e31-3aab-4e61-921c-5841c0cec8a8.png)

I'm not sure if there's anything `svg-lib` can do here when injecting the SVG in place of the text. Maybe locally override the a couple of text attributes? I don't have much experience with this stuff,  but will see if I can figure out a solution.

**Comment by rougier** [comment]
The outside of the tag is supposed to be transparent and will be colored with your window background color. If you select the tag however, the background will keep the background color (instead of highlight color). In your case, I think you need to set the DONE/TODO keyword to have no color. Reason is that the tag do not extend across linespace (but it might be doable).

Can you explain further what would be the output you want with the tag?

**Comment by DivineDominion** [comment]
I'd like the text background color to be removed (no background, or changed to the window background color), so that the old background color doesn't appear below the SVG for the tag.

Maybe I haven't thought this through, though 🤔 This might be a special case for org TODO keywords, but I don't think the background color of _any_ text that's being replaced with an SVG based image should be removed. There might be legitimate cases where you want a consistent background color, e.g. for a whole line; and removing the color for the tag would look weird.

Adding a special case to this svg-lib  for org TODO keywords doesn't make sense. It's up to me to fix this in the configuration. Am retracting this request :)
