### ISSUE TITLE
SVG in header/mode line example

### ISSUE THREAD

**Issue by darth-cheney** [rougier/svg-lib#22]
Can you add an example where you put, say, an svg progressbar indicating the cursor position in the header or modeline? In particular I'm interested in how this could be combined with nano-modeline

**Comment by rougier** [comment]
If you insert the string below in the modeline, it should work:

```lisp
(propertize "Progress" 'display (svg-lib-progress-bar .5 nil :width 9 :margin 1 :stroke 2 :padding 2))
```

**Comment by darth-cheney** [comment]
Excellent, that works great. Thanks

**Comment by darth-cheney** [comment]
Just wanted to follow up: I'm able to use the circular progress indicator to give me some sense of the cursor's position in a document (inside of nano-mode-line):
<img width="715" alt="Screen Shot 2022-08-02 at 6 08 31 PM" src="https://user-images.githubusercontent.com/1640299/182482014-2a090b99-0cf9-42bf-93d6-6414e19c52c2.png">
  
Works pretty well, though I'm not sure why there is extra space to the right

**Comment by rougier** [comment]
The regular string that is used to display the icon need to have the same width (2 spaces in that case)
