### ISSUE TITLE
VSCode icons support

### ISSUE THREAD

**Issue by grolongo** [rougier/svg-lib#27]
Hello, would it be possible for svg-lib to add support for VSCode icons?  
They use Creative Commons Attribution 4.0 International for their license and their repository is here:  
https://github.com/microsoft/vscode-icons

**Comment by rougier** [comment]
I think it might be possible. Note that you can modify the list of repositories such as to include it. Did you already made some experiments with them?

**Comment by grolongo** [comment]
So those icons are included with `company` and they work pretty well, but I didn't try to use them from your package directly.  
I'll do that with the examples from your demo and report back.

**Comment by grolongo** [comment]
So I tested after adding:
```elisp
(add-to-list 'svg-lib-icon-collections '("vscode-light" . "https://raw.githubusercontent.com/microsoft/vscode-icons/main/icons/light/%s.svg"))
(add-to-list 'svg-lib-icon-collections '("vscode-dark" . "https://raw.githubusercontent.com/microsoft/vscode-icons/main/icons/dark/%s.svg"))
```
Thing is vscode icons have 2 versions, light and dark, but I fail to see the difference when used with svg-lib, so I'm not sure if the two sources are necessary. Anyway here is the few test results, not sure if that's enough testing to be included in your package. Let me know.

![vscode-svg-test](https://user-images.githubusercontent.com/34292770/212349417-3d60b326-e862-4dfe-8a5a-46fdfe3078ef.png)

**Comment by rougier** [comment]
dark / light does not really mater since svg-lib will replace colors. If you want to use dark or light, you can define a style to be used with the icon.

**Comment by grolongo** [comment]
Indeed:
![Screenshot (250)](https://user-images.githubusercontent.com/34292770/216740147-a88bd3ee-ba41-4e7e-8978-b50849c6a039.png)

So can we add
```elisp
("vscode-light" .
     "https://raw.githubusercontent.com/microsoft/vscode-icons/main/icons/light/%s.svg")
```  
to `svg-lib-icon-collections`?

**Comment by rougier** [comment]
Yes. Maybe with the name `vscode` sinstead of `vscode-light`. Do you want to make a PR?

**Comment by grolongo** [comment]
I'm closing the issue.
