### ISSUE TITLE
svg-lib-icon: Don't draw background if `:background nil` is set

### ISSUE THREAD

**Issue by hedyhli** [rougier/svg-lib#34]
Hi, thanks for your useful library. I believe there is a feature that should be added to `svg-lib-icon` to make it more customizable.

[kind-icon](https://github.com/jdtsmith/kind-icon) gives icons next to candidates in emacs completion popups, which are fetched with `svg-lib-icon`. It would be great to have this function support not drawing a background to the fetched icons, so that the resulting SVG icons can adapt to the popup background, depending on whether the user is currently selecting it.

See this issue: jdtsmith/kind-icon#38.

Below is the result currently, svg-lib-icon drawing a background on the "`(x)`" icon.

<details open><summary>toggle</summary>
<img alt="image" width="500" src="https://user-images.githubusercontent.com/93749/141227979-9f22cbb6-8029-42f1-86b4-f4cdd03636b2.png"></details>

In the linked issue @jdtsmith also suggests a patch, which makes `svg-lib-icon` not draw a background if the user has set `:background nil`:

<details open><summary>toggle</summary>

```diff
@@ -212,10 +212,11 @@
   "Convert Emacs COLOR-NAME to #rrggbb form.
 If COLOR-NAME is unknown to Emacs, then return COLOR-NAME as-is."
   
-  (let ((rgb-color (color-name-to-rgb color-name)))
-    (if rgb-color
-        (apply #'color-rgb-to-hex (append rgb-color '(2)))
-      color-name)))
+  (when color-name
+    (let ((rgb-color (color-name-to-rgb color-name)))
+      (if rgb-color
+          (apply #'color-rgb-to-hex (append rgb-color '(2)))
+	color-name))))
 
 
 ;; SVG Library style build from partial specification
@@ -528,11 +529,12 @@
     (when (>= stroke 0.25)
       (svg-rectangle svg box-x box-y box-width box-height
                      :fill foreground :rx radius))
-    (svg-rectangle svg (+ box-x (/ stroke 2.0))
-                       (+ box-y (/ stroke 2.0))
-                       (- box-width stroke)
-                       (- box-height stroke)
-                       :fill background :rx (- radius (/ stroke 2.0)))
+    (when background
+      (svg-rectangle svg (+ box-x (/ stroke 2.0))
+                     (+ box-y (/ stroke 2.0))
+                     (- box-width stroke)
+                     (- box-height stroke)
+                     :fill background :rx (- radius (/ stroke 2.0))))
     
     (dolist (item (xml-get-children (car root) 'path))
       (let* ((attrs (xml-node-attributes item))
```

</details>

Here is what the popup would look like if `svg-lib-icon` supported transparency:

<details open><summary>toggle</summary>
<img alt="image" width="500" src="https://user-images.githubusercontent.com/93749/267366975-5013e589-fbee-4712-a9c3-56ccf21d4919.png">

(both screenshots used are provided by jdtsmith)
</details>

I believe it would be a nice addition to svg-lib to support fetching transparent icons so packages that use svg-lib can have more extensibility, as I'm sure the transparency option would be useful for other packages too.

**Comment by rougier** [comment]
Much better indeed. Could you (or @jdtsmith) make a PR?
