### ISSUE TITLE
svg-lib vs. svg-tag-mode vs. svg-icon

### ISSUE THREAD

**Issue by tarsius** [rougier/svg-lib#35]
Please clarify the relationship between these projects.

Does the former supersede the latter two? Assuming that is the case, do the latter two provide some functionality for which one might still prefer using them over the successor?

Does this (from https://github.com/rougier/svg-tag-mode/pull/14#issuecomment-864957447) mean fixes won't be backported?

> And for those interested, [svg-lib](https://github.com/rougier/svg-lib) might be more robust.

There is no hurry, but if you find the time, I would appreciate it if you could clarify these points and update the readme files to include or point to that information. Thanks!

**Comment by rougier** [comment]
- svg-lib provides only function for creating svg images and user is responsible for usage.
- svg-tag-mode makes use of svg-lib to replace some keywords with svg-lib objetcts (i.e. svg images)
- svg-icons is deprecated and is superseded by svg-lib (I need to add a warning and a redirection)

If you only need to replace some keyword by tags (via font-lock keywords), svg-tag-mode might be the easiest solution. If you need precised control, svg-lib might be a better solution. For example, in https://github.com/rougier/notes-list, I use svg-lib for the big icon and svg-tag-modes for the right tags.

**Comment by tarsius** [comment]
Thanks for the information!
