### ISSUE TITLE
SVG's Not Being Inserted

### ISSUE THREAD

**Issue by chookity-pokk** [rougier/svg-lib#38]
I have this and svg-tag-mode installed and when using tag mode I can get SVG's without a problem. But using `(insert-image (svg-lib-tag "TODO"))` doesn't insert anything. I tried the whole demo and never got anything to insert properly using svg-lib. Below is a screenshot of TODO as an svg tag and the highlighted section is what I get when running the svg lib tag for TODO. I tried several other words and I get the same result every time.

![image](https://github.com/rougier/svg-lib/assets/24358100/d56067fa-d077-4a71-ace1-5e2496381d63)

I am using Emacs 29.1 on Arch Linux and recently updated the svg packages this week.

Edit:
Another example with the pie progress bar.

![image](https://github.com/rougier/svg-lib/assets/24358100/d5218b81-2a26-402e-9f66-02dfe9a29b3b)

**Comment by chookity-pokk** [comment]
Okay, I ended up solving this by running `(svg-lib-button-mode 1)`. I'll open a PR shortly that will have that at the top of the demo file.

![image](https://github.com/rougier/svg-lib/assets/24358100/fc468ea8-45f1-439b-bbf2-cc282b035eb7)

**Comment by rougier** [comment]
For `svg-lib-button-mode` I think you only need to extract the line related to font-lock-properties.
