### ISSUE TITLE
vscode collection icons not rendered

### ISSUE THREAD

**Issue by noblekid96** [rougier/svg-lib#43]
I recently upgraded svg-lib to 0.3 and noticed that vscode collection svgs are not rendered. I use svg-lib in conjunction with kind-icon and after some troubleshooting with the author of kind-icon we traced the issue to svg-lib.

Tried running the following snippet with emacs 

```
(package-initialize)
(require 'svg-lib)
(insert-image (svg-lib-icon "symbol-event"
			    '( :collection "vscode"
			       :face font-lock-variable-name-face
			       :padding 0 :stroke 0 :margin 0 :radius 0
			       :height 1.0 :scale 1.0 :background nil)))
```
I expected this result
![image](https://github.com/rougier/svg-lib/assets/44386386/ea117612-bd96-4b85-b018-64826ff6d660)

but got this instead (no icon rendered). 
<img width="453" alt="image" src="https://github.com/rougier/svg-lib/assets/44386386/512b7de3-5199-4297-8ec1-0d2a548cc462">

I'm using Emacs 29.1 on MacOS (emacs-mac port) with Doom Emacs framework

I also checked that the vscode icons are in the right directory
![image](https://github.com/rougier/svg-lib/assets/44386386/91e8c04c-eaae-47f1-a3e1-e58e8ea5bd71)

Let me know if there is anything I can do to help troubleshoot

jdtsmith/kind-icon#42

**Comment by jdtsmith** [comment]
The error seems to have crept in a1e2607, which is after the version 0.3 tagged on elpa.

**Comment by rougier** [comment]
Same here. but `(insert-image (svg-lib-tag "[vscode:symbol-event]"))` is working. It is also the case for you?

**Comment by rougier** [comment]
This one also works:
```
(insert-image (svg-lib-icon "symbol-event" 'font-lock-variable-name-face
			    :collection "vscode"
			    :padding 0 :stroke 2 :margin 0 :radius 0
			    :height 1.0 :scale 1.0))
```
so my new code is wrong when I read the style

**Comment by jdtsmith** [comment]
Yes your 2nd works for me as well on the latest master, must be a style issue.
