### ISSUE TITLE
Appropriate way to change `font-size`?

### ISSUE THREAD

**Issue by StrictlyMonad** [rougier/svg-lib#45]
As the title mentions, I am somewhat struggling to change the `:font-size` value of the `svg-lib-style-default`. Adding the line below to `svg-tags-mode` (or even directly to `use-package svg-lib`) does not change it and I am confused to why that is.

```emacs-lisp
:config (plist-put svg-lib-style-default :font-size 13)
```

Can someone help me figure out how to resolve this issue? :blush:

**Comment by rougier** [comment]
We changed how default are computed. Can you try the lastest github version?

**Comment by StrictlyMonad** [comment]
I tried the latest commit and one thing I recall was that I wanted to increase the computed size with 1 px. Because I was lost on how to do this, I thought I should create this issue.

**Comment by rougier** [comment]
Sorry for delay. Did you solve your problem? If not, can you post a screenshot of the problem?

**Comment by StrictlyMonad** [comment]
Apologies for the late response, but after keeping the size of the SVG tags to the default calculated I can say that the new size grew on me. 😅

Appreciate the help nonetheless!
