### ISSUE TITLE
Putting svg-lib on GNU ELPA

### ISSUE THREAD

**Issue by skangas** [rougier/svg-lib#9]
Thanks for this package! I have not yet tested it very much, but it looks really, really good.

May I suggest that you put this on GNU ELPA, as a first step towards hopefully push for it to be included in Emacs itself? I think we could use it to improve the visual look of Emacs out-of-the-box.

Let me know if you need any help or have any questions about this.

**Comment by rougier** [comment]
It is actually my plan but I need to find time to do it. I've signed the paperwork and it's only a matter of applying the elpa procedure to submit it. Also, there are still problems wit the text size for some people and I've been unable to find the reason. Probably this is due to a difference in physical vs logical dpi but it is not consistent.

**Comment by rougier** [comment]
@skangas I've checked the [README](https://git.savannah.gnu.org/cgit/emacs/elpa.git/plain/README) which is a bit hard to read online (orgmode file without any rendering), but I've to admit instructions are not totally clear to me.

**Comment by skangas** [comment]
Thanks! That's really good news.

Indeed, the README is hard to read as just plain-text. (I hope to get to it eventually, unless someone else beats me to it.)

Basically, as a package author, all you should need to do is sending an email to emacs-devel@gnu.org saying that you want to add your package to GNU ELPA, and we will help you sort out the rest.

The only other thing to be aware of for GNU ELPA is the copyright assignment requirement, but that only applies to people who added more than 15 lines or so in total. I can see that no other contributors have done that so far, so that is also fine. But obviously going forward that's something to keep in mind before applying patches from others; they need to sign the copyright assignment first.

**Comment by skangas** [comment]
By the way, when you email emacs-devel, you could also consider mentioning the outstanding issue you're working on. If you go into some detail, perhaps there is someone there that can help.

Alternatively, there is also the [help-gnu-emacs](https://lists.gnu.org/mailman/listinfo/help-gnu-emacs) mailing list that is frequently read by several core contributors.

**Comment by skangas** [comment]
Excellent, thanks.
